# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
 pipelines:
  - pipeline: buildContosoAir # identifier for the resource used in pipeline resource variables
    source: Student1-65865752.ContosoAir # name of the pipeline that produces the artifact
    trigger:
     branches:
      include:
       - master

pool:
    name: default

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'a4c1010a-1b96-44be-8e04-f769b9e67d54'
    definition: '3'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Connection'
    subscriptionId: 'd39d322c-3f51-41ea-b098-ed9e1c800875'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-lod'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
    csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
    overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
    deploymentMode: 'Incremental'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webApp'
    WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'